/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author Fena
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setMinimumSize(new java.awt.Dimension(1000, 690));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Carta 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 390, 148, 152);

        jLabel2.setText("Carta 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 390, 148, 152);

        jButton1.setText("JUGAR!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 563, 90, 30);

        jLabel3.setText("Carta Crupier 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 110, 148, 152);

        jLabel4.setText("Carta Crupier 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 110, 148, 152);

        jTextField1.setEditable(false);
        jTextField1.setText("Cuenta Casa:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 210, 93, 30);

        jTextField2.setEditable(false);
        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 210, 40, 30);

        jTextField3.setEditable(false);
        jTextField3.setText("Cuenta Jug:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 560, 82, 30);

        jTextField4.setEditable(false);
        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(230, 560, 60, 30);

        jButton2.setText("Pedir Primera Carta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 563, 137, 30);

        jButton3.setText("Plantarse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 610, 515, 23);

        jLabel7.setText("Carta 3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 390, 148, 152);

        jLabel5.setText("Carta Crupier3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 110, 148, 152);

        jLabel6.setText("Carta Crupier 4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 110, 148, 152);

        jLabel8.setText("carta 4");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(600, 390, 148, 152);

        jButton4.setText("Pedir segunda carta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(580, 563, 140, 30);

        jTextField6.setEditable(false);
        jTextField6.setText("Apostado:");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(840, 40, 69, 30);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(920, 40, 56, 30);

        jButton5.setText("Pedir tercera carta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(740, 563, 130, 30);

        jLabel9.setText("carta 5");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(740, 390, 148, 152);

        jTextField5.setEditable(false);
        jTextField5.setText("Total:");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(840, 0, 68, 30);

        jTextField8.setEditable(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(920, 0, 56, 30);

        jButton6.setText("REGLAS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(130, 600, 90, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1090, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Random rnd=new Random();
int c1,c2,p1,p2,cc1,c3,p3,pcc1,pcc2,cc2,jugpts,ccpts;
double apu = 0,tot=0;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//c1=carta1 jugador  c2=carta2 jugador 
//p1 y p2 palos de las cartas
// c3 y p3 repite lo de arriba
//pcc1 y pcc2 palos carta crupier
//cc1 y cc2 cartas del crupier
//jugpts contador cartas de jugador
//ccpts contador cartas de crupier
       
//reincio de los valores al tocar jugar.
        
        //desbloquear boton pedir carta y JUgar        
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton3.setEnabled(false);
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
        
        jButton3.setText("Plantarse");
        
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        
        while(tot <= 0){
            tot = Double.parseDouble(JOptionPane.showInputDialog("Ingrese cantidad de dinero que desea poner en Juego"));
            jTextField8.setText(""+tot);
        }
        
        apu = Double.parseDouble(JOptionPane.showInputDialog("ingrese apuesta"));
        
    while (apu<=0){
                JOptionPane.showMessageDialog(null,"La apuesta minima debe ser mayor a cero");
    apu = Double.parseDouble(JOptionPane.showInputDialog("ingrese apuesta"));}
            
        
        while(apu > tot){
            
            
            apu = Double.parseDouble(JOptionPane.showInputDialog("La apuesta debe ser menor o igual al total" + "\nIngrese apuesta"));
        }
        
        //movido para que hablite los botones despues de poner la apuesta si no usuario puede cancelar y jugar igual
        jButton3.setEnabled(true);
        jButton2.setEnabled(true);
        //seteo del total despues de agregar la apuesta.
        tot=tot-apu;
        jTextField7.setText(""+apu);
        jTextField8.setText(""+tot);
        
        
       //asignacion de cartas y palos 
                            
       c1=rnd.nextInt(13)+1;
       p1=rnd.nextInt(4)+1;
       //System.out.println(c1);

       c2=rnd.nextInt(13)+1;
       p2=rnd.nextInt(4)+1;
       //System.out.println(c2);

       cc1=rnd.nextInt(13)+1;
       pcc1=rnd.nextInt(4)+1;
    
       
 
       jLabel1.setIcon(new ImageIcon (getClass().getResource("/img/"+c1+p1+".png")));
       jLabel1.setText("");

       jLabel2.setIcon(new ImageIcon (getClass().getResource("/img/"+c2+p2+".png")));
       jLabel2.setText("");

       jLabel3.setIcon(new ImageIcon (getClass().getResource("/img/"+cc1+pcc1+".png")));
       jLabel3.setText("");

       jLabel4.setIcon(new ImageIcon (getClass().getResource("/img/reves.png")));
       jLabel4.setText("");

        //valores para figuras jugador
        if (c1>10) {
            c1=10;
        }
        if (c2>10) {
            c2=10;
        }

        //valores para figuras crupier
        if (cc1>10) {
            cc1=10;
        }
        if (cc2>10) {
            cc2=10;
        }
        // puntajes despues de primera tirada

        jugpts=c1+c2;

        ccpts=cc1;        

        jTextField4.setText(""+jugpts);

        jTextField2.setText(""+ccpts);

//chequeo blackjack
        if (jugpts == 11 && (c1 == 1 || c2 == 1)) {
            jugpts= 21;
            apu = apu * 3;
            tot=tot+apu;
           
            jTextField8.setText(""+tot);
            jTextField4.setText(""+jugpts);
            JOptionPane.showMessageDialog(null, "BlackJack, has GANADO");
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton2.setEnabled(false);
            jButton1.setEnabled(true);
            //reseteo de apuesta
            apu = 0;
            jTextField7.setText("" + apu);
        }else {
            jButton1.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
        
        
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
int c4,p4;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // hacer visible carta  jugador 3
     jLabel7.setVisible(true);
     
    //habilita boton 2da carta 
     jButton4.setEnabled(true);
     
     
     c3=rnd.nextInt(13)+1;
     p3=rnd.nextInt(4)+1;

     jLabel7.setIcon(new ImageIcon (getClass().getResource("/img/"+c3+p3+".png")));
     jLabel7.setText("");

        //valores para figuras jugador
     if (c3>10) {
             c3=10;
     }

     //cuenta jugador 

     jugpts=jugpts+c3;
     jTextField4.setText(""+jugpts);

     //chequeo blackjack 

     if (jugpts==21) {
            
            jButton2.setEnabled(false);
            jButton3.setText("Verifique que tiene el crupier");
            jButton4.setEnabled(false);
            jButton1.setEnabled(false);
            
     }else if (jugpts>21) {
             jButton2.setEnabled(false);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             jButton1.setEnabled(true);
             
             //reseteo apu
             apu = 0;
             jTextField7.setText("" + apu);
             JOptionPane.showMessageDialog(null, "Perdio, Jugador Pierde Apuesta");
             // deshabilita boton 2da carta, sino al perder seguia tirando cartas si queria.
             jButton4.setEnabled(false);
             jButton5.setEnabled(false);
     }
     
     //deshabilita boton 1ra carta
     jButton2.setEnabled(false);
     
     
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange

 this.getContentPane().setBackground(new java.awt.Color(0, 102, 0));
//ocultar cartas no usadas
        
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        
        // iniciar con cartas dadas vueltas
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/img/reves.png")));
        jLabel1.setText("");
        
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/reves.png")));
        jLabel2.setText("");
        
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/reves.png")));
        jLabel3.setText("");
        
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/img/reves.png")));
        jLabel4.setText("");
        
        
        
    }//GEN-LAST:event_formPropertyChange
int k = 0;
int [] manocc=new int [5];
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //bloquear boton pedir carta y JUgar
        
        jButton4.setEnabled(false);
        jButton2.setEnabled(false);
        jButton1.setEnabled(false);
        jButton5.setEnabled(false);
       
        
       //segunda tercera carta crupier 
       //segunda tercera carta crupier 
       do {

            pcc2=rnd.nextInt(4)+1;
            manocc[k]=rnd.nextInt(13)+1;
            
            //chequeo blackjack de casa y puntaje
            
            if (manocc[k] == 1 && k == 0 && ccpts >= 10) {
                ccpts = 21;
            } else if (manocc[k] >= 10 && k == 0 && ccpts == 1) {
                ccpts = 21;
            }else if(manocc[k] > 10){
                ccpts=ccpts + 10;
            } else {
                ccpts=ccpts+manocc[k];
            }
            
            
            
            switch (k){
            case 0:
                    jLabel4.setIcon(new ImageIcon (getClass().getResource("/img/"+manocc[k]+pcc2+".png")));
                    jLabel4.setText("");
                    break;

            case 1: jLabel5.setVisible(true);
                    jLabel5.setIcon(new ImageIcon (getClass().getResource("/img/"+manocc[k]+pcc2+".png")));
                    jLabel5.setText("");  
                    break;
            case 2: jLabel6.setVisible(true);
                    jLabel6.setIcon(new ImageIcon (getClass().getResource("/img/"+manocc[k]+pcc2+".png")));
                    jLabel6.setText("");  
                    break;
            case 3: jLabel6.setVisible(true);
                    jLabel6.setIcon(new ImageIcon (getClass().getResource("/img/"+manocc[k]+pcc2+".png")));
                    jLabel6.setText("");  
                    break;
            case 4: jLabel6.setVisible(true);
                    jLabel6.setIcon(new ImageIcon (getClass().getResource("/img/"+manocc[k]+pcc2+".png")));
                    jLabel6.setText("");  
                    break;
            default: jLabel6.setVisible(true);
                     jLabel6.setIcon(new ImageIcon (getClass().getResource("/img/"+manocc[k]+pcc2+".png")));
                     jLabel6.setText("");  
                     break;
                
                  
            } 

            
            jTextField4.setText(""+jugpts);

            jTextField2.setText(""+ccpts);
              
            k++;
       }while (ccpts < 17);
        
        if(ccpts > 21){
            JOptionPane.showMessageDialog(null, "Mas de 21, Jugador Gana");
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton1.setEnabled(true);
            apu = apu * 1.5;
            tot=tot+apu;
            jTextField8.setText(""+tot);
        } else if(ccpts == 21 && k == 1){
            JOptionPane.showMessageDialog(null, "La Casa Obtuvo BlackJack. Pierde Apuesta");
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton1.setEnabled(true);   
        } else if(ccpts == jugpts) {
            JOptionPane.showMessageDialog(null, "Empate no Gana ni Pierde");
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton1.setEnabled(true);
            tot=tot+apu;          
            jTextField8.setText(""+tot);
        } else if(ccpts > jugpts){
            JOptionPane.showMessageDialog(null, "La Casa Gana. Pierde Apuesta");
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton1.setEnabled(true);

        } else{
            JOptionPane.showMessageDialog(null, "Has Ganado.");
            apu = apu * 1.5;
            tot=tot+apu;
            
            jTextField8.setText(""+tot);
          
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton1.setEnabled(true);
        }
      
      //reseteo apuesta
      apu = 0;
      jTextField7.setText(""+apu);
      //reseteo variable una vez que termine el juego para volver a jugar K              
      k=0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

 
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // hacer visible carta  jugador 4 e inhabilitar primer boton
        jLabel8.setVisible(true);
        jButton2.setEnabled(false);

        c4=rnd.nextInt(13)+1;
        p4=rnd.nextInt(4)+1;

        jLabel8.setIcon(new ImageIcon (getClass().getResource("/img/"+c4+p4+".png")));
        jLabel8.setText("");

           //valores para figuras jugador
        if (c4>10) {
                c4=10;
        }

//cuenta jugador 

        jugpts=jugpts+c4;
        jTextField4.setText(""+jugpts);

//chequeo blackjack 
 jButton5.setEnabled(true);
    if (jugpts==21) {
        jButton2.setEnabled(false);
        jButton3.setText("Verifique que tiene el crupier");
        jButton4.setEnabled(false);
        jButton1.setEnabled(false);
            
        
    }else if (jugpts>21) {
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton1.setEnabled(true);
        jButton5.setEnabled(false);
        
        //reseteo apuesta
        apu = 0;
        jTextField7.setText(""+apu);
        
        JOptionPane.showMessageDialog(null, "Mas de 21, Jugador Pierde Apuesta");
    }
   
    jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed
int c5,p5;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // hacer visible carta  jugador 5 e inhabilitar primer y segundo boton
        jLabel9.setVisible(true);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);

        c5=rnd.nextInt(13)+1;
        p5=rnd.nextInt(4)+1;

        jLabel9.setIcon(new ImageIcon (getClass().getResource("/img/"+c5+p5+".png")));
        jLabel9.setText("");

           //valores para figuras jugador
        if (c5>10) {
                c5=10;
        }

//cuenta jugador 

        jugpts=jugpts+c5;
        jTextField4.setText(""+jugpts);

//chequeo puntaje crupier, posibilidad de empate o blackjack y gane la casa.

        if (jugpts==21) {
            jButton2.setEnabled(false);
            jButton3.setText("Verifique que tiene el crupier");
            jButton4.setEnabled(false);
            jButton1.setEnabled(false);


        }else if (jugpts>21) {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton1.setEnabled(true);
            jButton5.setEnabled(false);
           
            //reseteo apuesta
            apu = 0;
            jTextField7.setText(""+apu);
            JOptionPane.showMessageDialog(null, "Mas de 21, Jugador Pierde Apuesta");
        }
               
                                            
        jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                // TODO add your handling code here:
                Form2 form2 = new Form2(); 
                form2.setVisible(true);                                                                                                                
                Form1.this.dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton3.setEnabled(false);
        jButton2.setEnabled(false);
 
        jButton1.setEnabled(true);

       
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
